version: '3'
services:

  db:
    container_name: db
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d/
      - db_init:/var/lib/postgresql/data
    networks:
      - app_network

  tasks:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5005:5005"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_init:

networks:
  app_network:
    driver: bridge
