"""Adding update date task field

Revision ID: 6e6e2dfafbfd
Revises: b938ae0bd4de
Create Date: 2020-05-22 10:10:27.525020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6e2dfafbfd'
down_revision = 'b938ae0bd4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('update_task_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'update_task_date')
    # ### end Alembic commands ###
